name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run on each push on the main branch
  push: { branches: ["main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - repo
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: sharansutrapu
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_languages: no
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 10
          plugin_languages_details: lines, percentage
          # Introduction (Joined year)
          plugin_introduction: yes
          plugin_introduction_title: yes

          # Calendar (This Year Graph)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
